In [1]:
# how to create a Numpy array?
# from a list
import numpy as np
np_array = np.array([1,2,3,4,5])
print(np_array,type(np_array))
np_array = np.array([1,2,3,4,5,'string is added'])#now the whole array will become a array of strings(Proving that these arrays are homogenious)
print(np_array,type(np_array),np_array.dtype)#np_array.dtype prints the datatype of the given array
#np_array.shape will tell us the value acording to the matrices i.e 1x2, 2x2, 3x3 etc.

[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'string is added'] <class 'numpy.ndarray'> <U21


In [2]:
# how to create a Numpy array?
# from scratch
arr1 = np.zeros((2,3))#this will create a 2x3 array of zeros
print(arr1)
arr2 = np.ones((2,3))#this will create a 2x3 array of ones
# we can also specify the datatype of the array
arr3 = np.ones((2,3),dtype=int)#this will create a 2x3 array of ones with integer datatype
print(arr2)
print(arr3) 

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
