In [2]:
# how to create a Numpy array?
# from a list
import numpy as np
np_array = np.array([1,2,3,4,5])
print(np_array,type(np_array))
np_array = np.array([1,2,3,4,5,'string is added'])#now the whole array will become a array of strings(Proving that these arrays are homogenious)
print(np_array,type(np_array),np_array.dtype)#np_array.dtype prints the datatype of the given array
#np_array.shape will tell us the value acording to the matrices i.e 1x2, 2x2, 3x3 etc.

[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'string is added'] <class 'numpy.ndarray'> <U21


In [3]:
# how to create a Numpy array?
# from scratch
arr1 = np.zeros((2,3))#this will create a 2x3 array of zeros
print(arr1)
arr2 = np.ones((2,3))#this will create a 2x3 array of ones
# we can also specify the datatype of the array
arr3 = np.ones((2,3),dtype=int)#this will create a 2x3 array of ones with integer datatype
print(arr2)
print(arr3)
arr4 = np.full((3,4),100)
print(arr4)
arr5 = np.eye(3) # creates a identity matrix and puts the given number as a number of diagonals of the matrix(identity matrix is a matrix which is 1 on its diagonals a zero everywhere else)
print(arr5)
arr6 = np.arange(1,11) # would create a array with elements 1-11 with 11 excluded 
print(arr6)
arr7 = np.arange(1,11,2)# would create a array with element 1-11 skipping 1 element b/w them
print(arr7)
#basically arange function is similar to range function which takes in (start,end,step)
arr8 = np.linspace(1,10,5) # this will create a array with 5 elements between 1 and 10 with equal spacing
print(arr8)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 1.    3.25  5.5   7.75 10.  ]


In [7]:
# Properties of Numpy arrays
arr = np.array([[1,2,3],[2,3,4],[8,9,10]])
print(arr.dtype) #datatype
print(arr.shape) #shape of array(mxn dimensions)
print(arr.size) #total number of elements
print(arr.ndim) #dimension of array

int64
(3, 3)
9
2


In [12]:
# Typecasting
float_arr = arr.astype(np.float64)#would typecast arr array to dtype float64 from int
print(float_arr.dtype)
print(float_arr)

float64
[[ 1.  2.  3.]
 [ 2.  3.  4.]
 [ 8.  9. 10.]]


In [20]:
# operations on array
arr = np.array([[1,2,3],[4,5,6]])
reshaped_arr = arr.reshape(3,2)
print(arr)

print("\n after reshaping")
print(reshaped_arr)

flattened_array = reshaped_arr.flatten()
print("\n after flattening\n",flattened_array)

[[1 2 3]
 [4 5 6]]

 after reshaping
[[1 2]
 [3 4]
 [5 6]]

 after flattening
 [1 2 3 4 5 6]


In [46]:
# indexing in arrays
# indexing in arrays is of 3 types:
# 1. normal indexing
# 2, boolean indexing
# 3 fancy indexing
arr = np.array([[1,2,3,4,5],[1,2,2,3,8],[3,5,4,3,4]])
print(arr)
flatten_arr = arr.flatten()
print(flatten_arr)
# 1. Normal Indexing
print(arr[2][2]) # works similar like we access a value in a matrix in mathematics
print(flatten_arr[3]) # this one is similar to accessing a value in a list in python but works in only 1 D arrays

# 2. Boolean Indexing
print(arr[arr<3])#we need to specify a condition and numbers for whom it is true are printed

# 3. Fancy Indexing
idx = [[1,2,0],[1,2,0]]
print(arr[idx])

[[1 2 3 4 5]
 [1 2 2 3 8]
 [3 5 4 3 4]]
[1 2 3 4 5 1 2 2 3 8 3 5 4 3 4]
4
4
[1 2 1 2 2]
[[[1 2 2 3 8]
  [3 5 4 3 4]
  [1 2 3 4 5]]

 [[1 2 2 3 8]
  [3 5 4 3 4]
  [1 2 3 4 5]]]


In [50]:
# slicing in arrays
# slicing in numpy arrays is similar to python lists.
# But slicing in numpy arrays is way faster because of a structural difference in how slicing is done. In python LIsts a seperate copy of og list is created when we do slicing 
# but in numpy arrays operations are performed based on a view and the memory isn't used and hence they are faster and less space consuming than python lists.
# but we can use .copy() function in case we need to create a copy of a array.

# To denote a complex number in python we have to use j 
# example:
complex_arr = np.array([2+3j,45+32j])
print(complex_arr,complex_arr.dtype)

[ 2. +3.j 45.+32.j] complex64
